document.addEventListener('DOMContentLoaded',function(event){var yasrRaterInDom=document.getElementsByClassName('yasr-rater-stars');if(yasrRaterInDom.length>0){yasrSetRatingOnLoad(yasrRaterInDom);}
var yasrRaterVVInDom=document.getElementsByClassName('yasr-rater-stars-visitor-votes');if(yasrRaterVVInDom.length>0){yasrVisitorVotesFront(yasrRaterVVInDom);}
var yasrMultiSetVisitorInDom=document.getElementsByClassName('yasr-multiset-visitors-rater');if(yasrMultiSetVisitorInDom.length>0){yasrRaterVisitorsMultiSet(yasrMultiSetVisitorInDom)}
if(yasrRaterVVInDom){if(yasrCommonData.visitorStatsEnabled==='yes'){var yasrStatsInDom=document.getElementsByClassName('yasr-dashicons-visitor-stats');if(yasrStatsInDom){yasrDrawTipsProgress(yasrStatsInDom);}}}
if(typeof yasrMostHighestRanking!=='undefined'){document.getElementById('yasr-highest-rated-posts').style.display='none';}});function yasrShowHighest(){document.getElementById('yasr-most-rated-posts').style.display='none';document.getElementById('yasr-highest-rated-posts').style.display='';}
function yasrShowMost(){document.getElementById('yasr-highest-rated-posts').style.display='none';document.getElementById('yasr-most-rated-posts').style.display='';}
function yasrDrawTipsProgress(yasrStatsInDom){var htmlIdChecked=false;for(var i=0;i<yasrStatsInDom.length;i++){(function(i){var htmlId='#'+yasrStatsInDom.item(i).id;var postId=yasrStatsInDom.item(i).getAttribute('data-postid');var data={action:'yasr_stats_visitors_votes',post_id:postId};var initialContent='<span style="color: #0a0a0a">Loading...</span>';tippy(htmlId,{content:initialContent,theme:'yasr',arrow:'true',arrowType:'round',onShow:function onShow(tip){if(htmlId!==htmlIdChecked){jQuery.post(yasrCommonData.ajaxurl,data,function(response){response=JSON.parse(response);tip.setContent(response);});}},onHidden:function onHidden(){htmlIdChecked=htmlId;}});})(i);}}
function yasrSetRaterValue(starSize,htmlId){starSize=parseInt(starSize);raterJs({starSize:starSize,step:0.1,showToolTip:false,readOnly:true,element:document.getElementById(htmlId),});}
function yasrSetRatingOnLoad(yasrRatingsInDom){for(var i=0;i<yasrRatingsInDom.length;i++){var htmlId=yasrRatingsInDom.item(i).id;var starSize=yasrRatingsInDom.item(i).getAttribute('data-rater-starsize');yasrSetRaterValue(starSize,htmlId);}}
function yasrVisitorVotesFront(yasrRaterVVInDom){for(var i=0;i<yasrRaterVVInDom.length;i++){(function(i){let rating=yasrRaterVVInDom.item(i).getAttribute('data-rating');let readonly=yasrRaterVVInDom.item(i).getAttribute('data-rater-readonly');let postId=yasrRaterVVInDom.item(i).getAttribute('data-rater-postid');let htmlId=yasrRaterVVInDom.item(i).id;let uniqueId=htmlId.replace('yasr-visitor-votes-rater-','');let starSize=parseInt(yasrRaterVVInDom.item(i).getAttribute('data-rater-starsize'));let nonce=yasrRaterVVInDom.item(i).getAttribute('data-rater-nonce');let isSingular=yasrRaterVVInDom.item(i).getAttribute('data-issingular');let containerVotesNumber='yasr-vv-votes-number-container-'+uniqueId;let containerAverageNumber='yasr-vv-average-container-'+uniqueId;let containerAfterStarsID='yasr-visitor-votes-container-after-stars-'+uniqueId;let spanBottom=false;if(rating===null&&readonly===null){let urlVisitorVotes='wp/v2/posts/'+postId+'?_fields=yasr_visitor_votes&_wpnonce='+yasrCommonData.nonce;fetch(yasrCommonData.restEndpoint+urlVisitorVotes).then(response=>{return response.json();}).then(data=>{readonly=data.yasr_visitor_votes.stars_attributes.read_only;if(data.yasr_visitor_votes.number_of_votes>0){rating=data.yasr_visitor_votes.sum_votes/data.yasr_visitor_votes.number_of_votes;}else{rating=0;}
rating=rating.toFixed(1);rating=parseFloat(rating);document.getElementById(containerVotesNumber).innerHTML=data.yasr_visitor_votes.number_of_votes;document.getElementById(containerAverageNumber).innerHTML=rating;yasrSetVisitorVotesRater(starSize,rating,postId,readonly,htmlId,uniqueId,nonce,isSingular,containerAfterStarsID);if(data.yasr_visitor_votes.stars_attributes.span_bottom!==false){spanBottom=data.yasr_visitor_votes.stars_attributes.span_bottom;let yasrTotalAverageContainer=document.getElementById(containerAfterStarsID);yasrTotalAverageContainer.insertAdjacentHTML('beforeend',spanBottom);}}).catch(err=>{});}else{yasrSetVisitorVotesRater(starSize,rating,postId,readonly,htmlId,uniqueId,nonce,isSingular,containerAfterStarsID);}})(i);}}
function yasrSetVisitorVotesRater(starSize,rating,postId,readonly,htmlId,uniqueId,nonce,isSingular,containerAfterStarsID){rating=parseFloat(rating);readonly=yasrTrueFalseStringConvertion(readonly);raterJs({starSize:starSize,rating:rating,step:1,showToolTip:false,readOnly:readonly,element:document.getElementById(htmlId),rateCallback:function rateCallback(rating,done){document.getElementById(containerAfterStarsID).innerHTML=yasrCommonData.loaderHtml;var data={action:'yasr_send_visitor_rating',rating:rating,post_id:postId,nonce_visitor:nonce,is_singular:isSingular};this.setRating(rating);this.disable();jQuery.post(yasrCommonData.ajaxurl,data,function(response){response=JSON.parse(response);document.getElementById(containerAfterStarsID).innerHTML=response;});done();}});}
function yasrRaterVisitorsMultiSet(yasrMultiSetVisitorInDom){var ratingObject="";var ratingArray=[];for(var i=0;i<yasrMultiSetVisitorInDom.length;i++){(function(i){var htmlId=yasrMultiSetVisitorInDom.item(i).id;var readonly=yasrMultiSetVisitorInDom.item(i).getAttribute('data-rater-readonly');readonly=yasrTrueFalseStringConvertion(readonly);var elem=document.querySelector("#"+htmlId);raterJs({starSize:16,step:1,showToolTip:false,readOnly:readonly,element:elem,rateCallback:function rateCallback(rating,done){var postId=elem.getAttribute('data-rater-postid');var setId=elem.getAttribute('data-rater-setid');var setIdField=elem.getAttribute('data-rater-set-field-id');rating=rating.toFixed(1);var vote=parseInt(rating);this.setRating(vote);ratingObject={postid:postId,setid:setId,field:setIdField,rating:vote};ratingArray.push(ratingObject);done();}});})(i);}
jQuery('.yasr-send-visitor-multiset').on('click',function(){var multiSetPostId=this.getAttribute('data-postid');var multiSetId=this.getAttribute('data-setid');jQuery('#yasr-send-visitor-multiset-'+multiSetPostId+'-'+multiSetId).hide();jQuery('#yasr-loader-multiset-visitor-'+multiSetPostId+'-'+multiSetId).show();var data={action:'yasr_visitor_multiset_field_vote',nonce:yasrMultiSetData.nonceVisitor,post_id:multiSetPostId,rating:ratingArray,set_type:multiSetId};jQuery.post(yasrCommonData.ajaxurl,data,function(response){jQuery('#yasr-loader-multiset-visitor-'+multiSetPostId+'-'+multiSetId).text(response);});});}
function yasrTrueFalseStringConvertion(string){if(typeof string==='undefined'||string===null||string===''){string=true;}
if(string==='true'||string==='1'){string=true;}
if(string==='false'||string==='0'){string=false;}
return string;}